{"uuid": "6b75f36e-09a5-4e0b-9fdb-f02d1c468bd5", "counter": 50, "stdout": "\u001b[0;31mfatal: [vm1]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'shell'\\n\\nThe error appears to be in '/root/profiler/ansible/playbook.yml': line 83, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n    - name: Display test results\\n      ^ here\\n\"}\u001b[0m", "start_line": 42, "end_line": 43, "runner_ident": "4d586ceb-47c0-438f-bb51-d83186e1d920", "event": "runner_on_failed", "pid": 13876, "created": "2024-07-22T18:55:13.331459+00:00", "parent_uuid": "c7d898e0-649d-5fc2-f1ae-000000000014", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "84d2905e-295d-40dc-82bf-f55eb1de3f4e", "play": "vms", "play_uuid": "c7d898e0-649d-5fc2-f1ae-000000000002", "play_pattern": "vms", "task": "Display test results", "task_uuid": "c7d898e0-649d-5fc2-f1ae-000000000014", "task_action": "debug", "resolved_action": "ansible.builtin.debug", "task_args": "", "task_path": "/root/profiler/ansible/playbook.yml:83", "host": "vm1", "remote_addr": "vm1", "res": {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'shell'\n\nThe error appears to be in '/root/profiler/ansible/playbook.yml': line 83, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Display test results\n      ^ here\n", "_ansible_no_log": false}, "start": "2024-07-22T18:55:13.314637+00:00", "end": "2024-07-22T18:55:13.331308+00:00", "duration": 0.016671, "ignore_errors": null, "event_loop": null, "uuid": "6b75f36e-09a5-4e0b-9fdb-f02d1c468bd5"}}