{"uuid": "caa96acd-5af6-4c34-894e-79d50d2d553e", "counter": 50, "stdout": "\u001b[0;31mfatal: [vm1]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'shell'\\n\\nThe error appears to be in '/root/profiler/ansible/playbook.yml': line 83, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n    - name: Display test results\\n      ^ here\\n\"}\u001b[0m", "start_line": 42, "end_line": 43, "runner_ident": "54d62970-0587-41d7-bf1a-c9cdace45850", "event": "runner_on_failed", "pid": 94537, "created": "2024-07-19T16:14:05.347841+00:00", "parent_uuid": "d9323c46-fa61-4999-7123-000000000014", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "396838a5-ce6d-4e95-a17e-3b62cb633e2e", "play": "vms", "play_uuid": "d9323c46-fa61-4999-7123-000000000002", "play_pattern": "vms", "task": "Display test results", "task_uuid": "d9323c46-fa61-4999-7123-000000000014", "task_action": "debug", "resolved_action": "ansible.builtin.debug", "task_args": "", "task_path": "/root/profiler/ansible/playbook.yml:83", "host": "vm1", "remote_addr": "vm1", "res": {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'shell'\n\nThe error appears to be in '/root/profiler/ansible/playbook.yml': line 83, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Display test results\n      ^ here\n", "_ansible_no_log": false}, "start": "2024-07-19T16:14:05.332444+00:00", "end": "2024-07-19T16:14:05.347624+00:00", "duration": 0.01518, "ignore_errors": null, "event_loop": null, "uuid": "caa96acd-5af6-4c34-894e-79d50d2d553e"}}