{"uuid": "4e9ef787-66db-4c35-9830-e01770ca9385", "counter": 50, "stdout": "\u001b[0;31mfatal: [vm1]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'shell'\\n\\nThe error appears to be in '/root/profiler/ansible/playbook.yml': line 83, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n    - name: Display test results\\n      ^ here\\n\"}\u001b[0m", "start_line": 42, "end_line": 43, "runner_ident": "21a5bb71-37f2-4485-88c2-d25afe426c30", "event": "runner_on_failed", "pid": 9560, "created": "2024-07-22T18:02:24.433136+00:00", "parent_uuid": "c7d898e0-649d-8b83-f902-000000000014", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "97541b15-f035-41d6-9513-f63c04b1a9b7", "play": "vms", "play_uuid": "c7d898e0-649d-8b83-f902-000000000002", "play_pattern": "vms", "task": "Display test results", "task_uuid": "c7d898e0-649d-8b83-f902-000000000014", "task_action": "debug", "resolved_action": "ansible.builtin.debug", "task_args": "", "task_path": "/root/profiler/ansible/playbook.yml:83", "host": "vm1", "remote_addr": "vm1", "res": {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'shell'\n\nThe error appears to be in '/root/profiler/ansible/playbook.yml': line 83, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Display test results\n      ^ here\n", "_ansible_no_log": false}, "start": "2024-07-22T18:02:24.419171+00:00", "end": "2024-07-22T18:02:24.432983+00:00", "duration": 0.013812, "ignore_errors": null, "event_loop": null, "uuid": "4e9ef787-66db-4c35-9830-e01770ca9385"}}